# Generated by Django 4.1.3 on 2022-11-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='main_url',
            field=models.URLField(max_length=500),
        ),
    ]
