# Generated by Django 4.1.3 on 2022-11-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_main_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='main_url',
            field=models.URLField(error_messages={'unique': 'Short URL for this URL already exists.'}, max_length=500, unique=True),
        ),
    ]
