# Generated by Django 4.1.3 on 2022-12-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_url_main_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['created', 'id']},
        ),
    ]
